# Generated by Django 5.2.7 on 2025-12-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caategory',
            new_name='category',
        ),
    ]
