# Generated by Django 5.2.7 on 2025-12-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_caategory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sctive',
            new_name='active',
        ),
    ]
